---
title: "Data Cleaning - Cycle 02"
author: "Cleverson Oliveira"
date: "`r format(Sys.time(), '%d/%m/%Y')`"
output:
  html_document:
    highlight: textmate
    logo: logo.png
    theme: jou
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: no
    df_print: paged
    code_folding: hide
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# Imports

```{r imports}
library(tidyverse)
library(janitor)
library(skimr)
library(gtsummary)
library(kableExtra)
library(summarytools)
library(gridExtra)
```

# Data Collection

You can also embed plots, for example:

```{r collection, echo=FALSE}
library(readr)
df2 <- read_csv("../dataset/train.csv")
View(df2)
glimpse(df2)
```

# Column Description

```{r, echo=FALSE}
variables <- df2 %>% names()
description <- c(
  "Unique ID for the customer",
  "Gender of the customer",
  "Age of the customer",
  "Customer has DL (yes/no)",
  "Unique code for the region of the customer",
  "Customer already has Vehicle Insurance (yes/no)",
  "Age of the Vehicle",
  "Customer got his/her vehicle damaged in the past (yes/no)",
  "The amount customer needs to pay as premium in the year",
  "Anonymized Code for the channel of outreaching to the customer ie. Different Agents, Over Mail, Over Phone, In Person, etc.",
  "Number of Days, Customer has been associated with the company",
  "Customer is interested in car insurance (yes/no)"
)

df_description <- tibble(variables = variables,
                  description = description)

kable(df_description, format = "html") %>% 
kableExtra::kable_styling(bootstrap_options = "striped", full_width = FALSE)
```

# Data Cleaning

```{r data cleaning}
df2 %>% names()

df2 <-  janitor::clean_names(df2, case = "snake") %>% # change the font
        rename(days_associated = vintage, 
               health_annual_paid = annual_premium) %>% # rename columns
        #Use across() with mutate() to apply a transformation  to multiple columns in a tibble
        mutate(
                        #columns          , function
                across(where(is.character), tolower),
                
                driving_license = ifelse(driving_license==1, "yes", "no"),
                
                previously_insured = ifelse(previously_insured==1, "yes", "no"),
                
                response = ifelse(response==1, "yes", "no"),
                
                vehicle_age = case_when(
                                        vehicle_age == "< 1 year" ~ "below_1_year",
                                        vehicle_age == "1-2 year" ~ "between_1_2_years",
                                        vehicle_age == "> 2 years" ~ "over_2_years"
                                        )
              ) %>% 
                              # categorical data
        mutate_if(is.character, as.factor) 
# checking the levels
table(df2$response)
table(df2$previously_insured)
  
        # Make sure yes is the first level of factor response
df2 <- df2 %>%  mutate( response           = factor(response, levels=c("yes", "no")),
                        previously_insured = factor(previously_insured, levels=c("yes", "no")),
                        driving_license    = factor(driving_license, levels=c("yes", "no")),
                        vehicle_damage     = factor(vehicle_damage, levels=c("yes", "no"))
              )
# checking the change of levels
table(df2$response)
table(df2$previously_insured)

df2 %>% names()

glimpse(df2)

saveRDS(df2, "df2.rds")
```

## Data Types

```{r}
str(df2)

lapply(df2, class) # give a list with classes of df1
unlist(lapply(df2, class))

      # column     values
tibble(variables = names(df2), 
       type      = unlist(lapply(df2, class)))
```

## Descriptive Statistics

### Data Structure

```{r}
skim(df2, -id, -region_code, -policy_sales_channel) # excluding identification columns
```

### General Overview

```{r}
# checking categorical levels
df2 %>% 
  select(-id) %>% 
  tbl_summary(# saying that a column is categorical forces the rstudio to show all categories
    
    type = list(response           ~ "categorical",
                driving_license    ~ "categorical",
                previously_insured ~ "categorical",
                vehicle_damage     ~ "categorical"),
    
    digits = list(all_categorical() ~ c(0, 2), # decimal places for numbers (0) and percentage (2)
                  all_continuous()  ~ c(1, 2)), 
    
    statistic = list(all_categorical() ~ "{n} ({p}%)", # numbers and percentage
                     all_continuous()  ~ "{median} ({p25}, {p75})"), 
    
    include = everything()
  )
```

### Numerical Statistics

```{r, echo=FALSE}
num_attributes <- df2 %>% 
                  select(age, health_annual_paid, days_associated)

desciptive_tab <- descr(num_attributes, style="rmarkdown") %>%  
                  round(2)

kable(data.frame(desciptive_tab), format="html") %>% 
      kableExtra::kable_styling(bootstrap_options = "striped", full_width=FALSE)
```

## Visualitzation

### Numerical Attributes

```{r, echo=FALSE}
num_attributes <- df2 %>% 
                  select(age, health_annual_paid, days_associated)

age_plt <- num_attributes %>% 
           ggplot(aes(x=age)) + 
           geom_histogram(aes(y=after_stat(density)), binwidth=1, color="gray", fill="lightblue", alpha=0.5) + 
           geom_density(color="blue") +
           labs(x="Age", y="Density", title="Customer Age Distribution") + 
           theme_minimal()
```

```{r, echo=FALSE}
paid_plt <- num_attributes %>% 
            ggplot(aes(x=health_annual_paid)) + 
            geom_histogram(aes(y=after_stat(density)), binwidth=10000, color="gray", fill="lightblue", alpha=0.5) + 
            geom_density(color="blue") +
            labs(x="Health Annual Paid", y="Density", title="Customer Payments \nDistribution") + 
            theme_minimal()
```

```{r, echo=FALSE}
days_plt <- num_attributes %>% 
            ggplot(aes(x=days_associated)) + 
            geom_histogram(aes(y=after_stat(density)), binwidth=5, color="gray", fill="lightblue", alpha=0.5) + 
            geom_density(color="blue") +
            labs(x="Health Annual Paid", y="Density", title="Customer Days \nAssociated Distribution") + 
            theme_minimal()
```

```{r, echo=FALSE}
grid.arrange(age_plt, paid_plt, days_plt, ncol=3)
```

## Categorical Attributes

```{r, echo=FALSE}
num_names <- names(num_attributes)
cat_attributes <- df2 %>% 
  select(-id, -one_of(num_names))
```

```{r, echo=FALSE}
gender_plt <- cat_attributes %>% 
              ggplot(aes(x=gender)) +
              geom_bar(aes(fill=gender)) +
              labs(x="Gender", y="Quantity", title="Customers Gender") + 
              theme_minimal()

driving_license_plt <- cat_attributes %>% 
                       ggplot(aes(x=driving_license)) +
                       geom_bar(aes(fill=driving_license)) +
                       labs(x="Driving License", y="Quantity", title="Customers \nDriving License") +
                       theme_minimal()

region_code_plt <- cat_attributes %>% 
                   ggplot(aes(x=region_code)) +
                   geom_bar(aes(fill=factor(region_code)), show.legend = FALSE) +
                   labs(x="Region Code", y="Quantity", title="Customers \nRegion Code") + 
                   theme_minimal()

previously_insured_plt <- cat_attributes %>% 
                          ggplot(aes(x=previously_insured)) +
                          geom_bar(aes(fill=previously_insured)) +
                          labs(x="Previously Insured", y="Quantity", title="Customers \nPreviously Insured") + 
                          theme_minimal()

vehicle_age_plt <- cat_attributes %>% 
                   ggplot(aes(x=vehicle_age)) +
                   geom_bar(aes(fill=vehicle_age)) +
                   labs(x="Vehicle Age", y="Quantity", title="Customers \nVehicle Age") + 
                   theme_minimal()

vehicle_damage_plt <- cat_attributes %>% 
                      ggplot(aes(x=vehicle_damage)) +
                      geom_bar(aes(fill=vehicle_damage)) +
                      labs(x="Vehicle Damage", y="Quantity", title="Customers \nVehicle Damage") + 
                      theme_minimal()

policy_sales_channel_plt <- cat_attributes %>% 
                            ggplot(aes(x=policy_sales_channel)) +
                            geom_bar(aes(fill=factor(policy_sales_channel)), show.legend = FALSE) +
                            labs(x="Police Sales Channel", y="Quantity", title="Customers Police \nSales Channel") + 
                            theme_minimal()

response_plt <- cat_attributes %>% 
                ggplot(aes(x=response)) +
                geom_bar(aes(fill=response)) +
                labs(x="Response", y="Quantity", title="Customers Response") + 
                theme_minimal()
```

```{r, echo=FALSE}
grid.arrange(gender_plt, driving_license_plt, region_code_plt, previously_insured_plt, vehicle_age_plt, ... =                        vehicle_damage_plt, policy_sales_channel_plt, response_plt, ncol=2, nrow=4)
```
